export const ASSET_ACTIONS = {
  GET_ALL_ASSETS: 'GET_ALL_ASSETS',
  GET_ONE_ASSET: 'GET_ONE_ASSET',
  CREATE_ASSET: 'CREATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
}

export const EMPLOYEE_ACTIONS = {
  GET_ALL_EMPLOYEES: 'GET_ALL_EMPLOYEES',
  GET_ONE_EMPLOYEE: 'GET_ONE_EMPLOYEE',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
}

export const ASSIGN_ACTIONS = {
  GET_EMPLOYEE_SELECTED: 'GET_EMPLOYEE_SELECTED',
  GET_ASSET_SELECTED: 'GET_ASSET_SELECTED',
  CANCEL_EMPLOYEE_SELECTED: 'CANCEL_EMPLOYEE_SELECTED',
  DELETE_ASSET: 'DELETE_ASSET',
  APPLY_ASSIGN: 'APPLY_ASSIGN',
}
